### ISSUE TITLE
Hangs

### ISSUE THREAD

**Issue by ziflex** [currantlabs/ble#36]
Hi there,

I have noticed, that ```ble``` periodically hangs and stops sending information from a device (I run it with allowDup=true). I.e. it sends adv for some period (e.g. 20 seconds) and then stops.

The time when it hangs not constant. It may hangs in 30 seconds or in 1-2 minutes. Or even longer.

**Comment by ziflex** [comment]
Here is some more information.
I killed my hanged process with ```kill -ABRT``` and got a trace of all goroutines.
Here is the list of goroutines from BLE pacakge:

```sh
goroutine 7 [syscall, 7 minutes]:
syscall.Syscall(0x0, 0x3, 0xc4201b5000, 0x1000, 0x0, 0x100000000001000, 0xc42003fea8)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:18 +0x5
github.com/blent/beagle/vendor/golang.org/x/sys/unix.read(0x3, 0xc4201b5000, 0x1000, 0x1000, 0x7bf182, 0xc42003feb8, 0xc42003fec8)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:803 +0x55
github.com/blent/beagle/vendor/golang.org/x/sys/unix.Read(0x3, 0xc4201b5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/golang.org/x/sys/unix/syscall_unix.go:113 +0x49
github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci/socket.(*Socket).Read(0xc42016b8e0, 0xc4201b5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci/socket/socket.go:129 +0x119
github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci.(*HCI).sktLoop(0xc420138180)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci/hci.go:267 +0xe1
created by github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci.(*HCI).Init
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci/hci.go:146 +0x5fd

goroutine 34 [select, 7 minutes]:
github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci.(*HCI).Accept(0xc420138180, 0x0, 0x0, 0x0, 0x0)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci/gap.go:141 +0x1c4
github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux.NewDevice.func1(0xc420138180, 0x203, 0xc4202141e0)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/device.go:38 +0x4b
created by github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux.NewDevice
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/device.go:58 +0x19c

goroutine 39 [chan receive (nil chan), 7 minutes]:
github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux.(*Device).Scan(0xc42020c5c0, 0xe4dde0, 0xc420012338, 0x418001, 0xc42024a000, 0x95d3c0, 0x1)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/device.go:149 +0xa7
github.com/blent/beagle/vendor/github.com/currantlabs/ble.Scan(0xe4dde0, 0xc420012338, 0x1, 0xc42024a000, 0x0, 0x0, 0x0)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/gatt.go:93 +0x1d6
github.com/blent/beagle/src/core/discovery/devices.(*BleDevice).start(0xc420210ae0, 0xe4dde0, 0xc420012338, 0xc42020f380, 0xc42020f3e0)
	/home/tvoronov/Work/src/github.com/blent/beagle/src/core/discovery/devices/device-ble.go:84 +0x8b
created by github.com/blent/beagle/src/core/discovery/devices.(*BleDevice).Scan
	/home/tvoronov/Work/src/github.com/blent/beagle/src/core/discovery/devices/device-ble.go:51 +0xbf


```

**Comment by ziflex** [comment]
I think the problem is here, since it's the only place where it may hang.

https://github.com/currantlabs/ble/blob/master/linux/hci/socket/socket.go#L129

The question is - how to debug ?

**Comment by ziflex** [comment]
Tested on C.H.I.P. with Debian 8 - same result.

**Comment by deadprogram** [comment]
Hi @ziflex not sure about your specific issue, but I was unable to get CHIP working with ble package at all: https://github.com/currantlabs/ble/issues/28

**Comment by ziflex** [comment]
@deadprogram weird. on my CHIP it works, but wit the same issue that I described above.
But I compiled my app on CHIP itself. How did you compile it ?

**Comment by deadprogram** [comment]
I do not think it matters where you compile, so much as which kernel you are running? what is the output for you when you run `uname -a`on your CHIP?

**Comment by ziflex** [comment]
@deadprogram 

```sh
Linux chip 4.4.13-ntc-mlc #1 SMP Tue Dec 6 21:38:00 UTC 2016 armv7l GNU/Linux
```

**Comment by deadprogram** [comment]
@ziflex I was trying to use the built-in BLE adaptor, not an external one.

**Comment by ziflex** [comment]
Ok, I tried to use laptop' builtin BLE adapter and looks like it works stable.
So, not sure, whether it's problem of hardware or the library.

P.s. btw, comparatively to paypal/gatt, this lib consumes much less memory.

**Comment by ziflex** [comment]
Upd: Tried to run with laptop' builtin adapter and result is much better - it lasted longer. Almost 16 minutes.
App was running for 26 minutes, 8 of them it hanged:

```sh
goroutine 7 [syscall, 8 minutes]:
syscall.Syscall(0x0, 0x3, 0xc4201b5000, 0x1000, 0x0, 0x100000000001000, 0xc42003bea8)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:18 +0x5
github.com/blent/beagle/vendor/golang.org/x/sys/unix.read(0x3, 0xc4201b5000, 0x1000, 0x1000, 0x7bf9c2, 0xc42003beb8, 0xc42003bec8)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:803 +0x55
github.com/blent/beagle/vendor/golang.org/x/sys/unix.Read(0x3, 0xc4201b5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/golang.org/x/sys/unix/syscall_unix.go:113 +0x49
github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci/socket.(*Socket).Read(0xc42016d900, 0xc4201b5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci/socket/socket.go:129 +0x119
github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci.(*HCI).sktLoop(0xc42013a180)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci/hci.go:267 +0xe1
created by github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci.(*HCI).Init
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci/hci.go:146 +0x5fd

goroutine 34 [select, 26 minutes]:
github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci.(*HCI).Accept(0xc42013a180, 0x0, 0x0, 0x0, 0x0)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/hci/gap.go:141 +0x1c4
github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux.NewDevice.func1(0xc42013a180, 0x203, 0xc4202261b0)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/device.go:38 +0x4b
created by github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux.NewDevice
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/device.go:58 +0x19c

goroutine 39 [chan receive (nil chan), 26 minutes]:
github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux.(*Device).Scan(0xc420210500, 0xe4ede0, 0xc42000c358, 0x418001, 0xc420252000, 0x984920, 0x1)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/linux/device.go:149 +0xa7
github.com/blent/beagle/vendor/github.com/currantlabs/ble.Scan(0xe4ede0, 0xc42000c358, 0x1, 0xc420252000, 0x0, 0x0, 0x0)
	/home/tvoronov/Work/src/github.com/blent/beagle/vendor/github.com/currantlabs/ble/gatt.go:93 +0x1d6
github.com/blent/beagle/src/core/discovery/devices.(*BleDevice).start(0xc4202069e0, 0xe4ede0, 0xc42000c358, 0xc4202052c0, 0xc420205320)
	/home/tvoronov/Work/src/github.com/blent/beagle/src/core/discovery/devices/device-ble.go:84 +0xe5
created by github.com/blent/beagle/src/core/discovery/devices.(*BleDevice).Scan
	/home/tvoronov/Work/src/github.com/blent/beagle/src/core/discovery/devices/device-ble.go:52 +0xbf

```

**Comment by ziflex** [comment]
Now I start thinking that probably it's a hardware issue.

@deadprogram does ble work on non-CHIP machine ?

**Comment by ziflex** [comment]
On OS X it works very stable. Without any hangs.

**Comment by ziflex** [comment]
Ok, I'm narrowing down the possible cause of the issue.
I have tested the lib on another Linux machine and it has the same issue - after some period of time it stops receiving information from a device. 

I may try it once on Ubuntu (this machine was running Fedora as well). But my guess is that it's an issue of BlueZ.

**Comment by deadprogram** [comment]
Hi @ziflex while debugging https://github.com/currantlabs/ble/issues/34 I have tracked down the problem when attempting to connect to the second peripheral to blocking on the very same `unix.Read()` call.

Anyone else trying this, or running into the same kind of issues? Let's combine forces to try to find a solution!

**Comment by ziflex** [comment]
@deadprogram which version of BlueZ are you using?

**Comment by deadprogram** [comment]
@ziflex should the version of BLueZ matter? I do not think there is any dependency between ble and BlueZ, since ble takes direct control of the HCI adaptor.

In any case:

```
$ bluetoothd -v
5.37
```

**Comment by ziflex** [comment]
@deadprogram yeah, you are right. I have notice that I don't have BlueZ on my machine anymore. And now I'm wondering, could it be a reason of hangs that I have experienced? Try to remove it. Maybe there are conflicts when BlueZ tries to get control of the HCI.

**Comment by deadprogram** [comment]
Once ble takes control over the HCI adaptor, nothing else can access it. In fact, once I run ble I have to reboot my machine to free up the adaptor for bluez. I do not think the problem is related to that.

So I think there is the same symptom, but perhaps different root causes here. While searching thru what Noble does, I found this code that might be specific to your particular timeout issue:

https://github.com/sandeepmistry/node-bluetooth-hci-socket/commit/c5d7f8455a33d1da3ccd3915dc20a32f38c91182

More info on this bug here: https://github.com/sandeepmistry/noble/issues/242

In my case, I am never able to establish the second simultaneous connection.

**Comment by ziflex** [comment]
@deadprogram I will try to recreate the issue again this weekend.

**Comment by ziflex** [comment]
@deadprogram what's your current kernel version ?

**Comment by deadprogram** [comment]
Hi @ziflex 

```
$ uname -r
4.4.0-78-generic
```

**Comment by ziflex** [comment]
@deadprogram on my Fedora 25 I have this version
``sh
4.10.15-200.fc25.x86_64
``

The situation has been improved, but it still hangs. Originally, I thought  it's gone, but the time before it hangs just has changed.

**Comment by deadprogram** [comment]
That what leads to wonder about the opening of the extra socket as Noble does? That would appear to be intended to address your specific issue.

**Comment by ziflex** [comment]
@deadprogram sounds like a dirty hack.
wondering how other BLE solutions handle this.

**Comment by deadprogram** [comment]
Several of the other BLE libs use BlueZ, so we have to go spelunking thru that code to know for sure. 

But I personally recommend that we do what https://github.com/sandeepmistry/noble does, since the maintainer of that project is quite active and knowledgeable.

**Comment by ziflex** [comment]
@deadprogram we may try. But looks like Noble has BlueZ as a dependency as well.

https://github.com/sandeepmistry/noble#ubuntudebianraspbian

**Comment by deadprogram** [comment]
I suppose I was mistaken. When I looked thru https://github.com/sandeepmistry/node-bluetooth-hci-socket I did not notice any dependency.

**Comment by jovandeginste** [comment]
@deadprogram @ziflex Did you find a solution to this? I'm not sure I have the same thing, but I try to scan my bluetooth scale using a Pi Zero W (with BLE onboard). First I made an eternal loop to scan for the scale, and read the data if it was online. However, I noticed that the loop would stop working after some time (usually it worked for at least half an hour, sometimes even several hours, before hanging in the scan).

This sounds similar to your issue?

This is the core part (specific commit for future reference in case this is solved): [bluetooth.go](https://github.com/jovandeginste/medisana-bs/blob/54829eb2d47cb3d7732cb7db9ffa0866bda6846f/bluetooth.go)

I removed the `for` loop to prevent the hanging, and now run the binary every minute through crond (with a scan duration of about 50s). This works for a whole day (instead of about an hour).

The `for` loop in the code was from line 24 until the end of the `func` (line 64).

Any suggestions are welcome! While the solution with crond works, it would be much nicer and more efficient if this were an internal loop...

**Comment by wcwynn** [comment]
@jovandeginste For what its worth, I encountered a similar problem on a Pi 3.  The issue was not that a hang would occur after some duration of time scanning but rather that a scan would hang when starting to scan.  When the hang occurred, killing the process resulted in a trace of goroutines looked strangely similar to what has been previously shared in this issue.  Disabling BlueZ entirely on the Pi (and ensuring that the scanning is started only from a process run with significant privilege) seemed to resolve the problem.  Also, even after disabling BlueZ, it seemed as if even just a single failed attempt to start scanning from a process without sufficient privilege resulted in subsequent problems (i.e. a start scan hang in the future).  So I'd recommend always rebooting if accidentally attempting to start scanning non-root.

I realize this does explain the root cause of the problem, but I wanted to share the steps I took to mitigate the problem in the hopes that it helps others and/or leads to identifying the underlying cause.

**Comment by jovandeginste** [comment]
@wcwynn You may be completely right about BlueZ. I have it installed because I had a Python script before that did the same thing, and I needed to debug bluetooth to get everything working. I will try disabling BlueZ entirely and test it for a while. I do believe it may be the "start scan" that hangs.

I did notice that, if my go-code was running and I started the python script  too, the go-code hung until killed.

**Comment by jovandeginste** [comment]
@wcwynn It seems to have helped! I now changed some timing parameters since I missed some packets, but the code has not stopped since yesterday. Thanks for the hint!

**Comment by ziflex** [comment]
@jovandeginste I'm currently don't have enough time to dig into this issue. But I have noticed, that it's more stable on the latest kernel.

**Comment by jovandeginste** [comment]
@ziflex Ok cool! After changing more stuff, the code started hanging again. I'll check what could be the reason, maybe the timing is too short now?

**Comment by jovandeginste** [comment]
Found some bugs due to my refactoring. Running the tests again (will take a while, of course)

**Comment by jovandeginste** [comment]
... but it was still hanging afterwards. I've tweaked some of the timings again, let's see what happens now!
