### ISSUE TITLE
fatal error: concurrent map writes / ble.DiscoverProfile() gets stuck

### ISSUE THREAD

**Issue by matti777** [currantlabs/ble#46]
I'm getting the following error when calling ble.Connect():

```
2017/07/25 16:13:59 Unhandled event: xpc.Dict{"kCBMsgId":54, "kCBMsgArgs":xpc.Dict{"kCBMsgArgServiceStartHandle":10, "kCBMsgArgDeviceUUID":xpc.UUID{0x26, 0x80, 0x8d, 0x10, 0xb, 0xa8, 0x46, 0xfb, 0xbb, 0x58, 0xa2, 0x7e, 0xe1, 0x90, 0xc, 0x7c}, "kCBMsgArgServiceEndHandle":65535}}
fatal error: concurrent map writes

goroutine 17 [running, locked to thread]:
runtime.throw(0x44aebec, 0x15)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:596 +0x95 fp=0xc42004da28 sp=0xc42004da08
runtime.mapassign(0x4422340, 0xc42015e0f0, 0xc42004db88, 0xc4201fb600)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/hashmap.go:499 +0x667 fp=0xc42004dac8 sp=0xc42004da28
github.com/currantlabs/ble/darwin.(*Device).conn(0xc42008c500, 0xc4201f0c00, 0x44a7755)
	/Users/matti/go/src/github.com/currantlabs/ble/darwin/device.go:500 +0x414 fp=0xc42004dbc0 sp=0xc42004dac8
github.com/currantlabs/ble/darwin.(*Device).HandleXpcEvent(0xc42008c500, 0xc4201f0bd0, 0x0, 0x0)
	/Users/matti/go/src/github.com/currantlabs/ble/darwin/device.go:448 +0x190f fp=0xc42004de20 sp=0xc42004dbc0
github.com/raff/goble/xpc.handleXpcEvent(0x4a00ac0, 0xc420051de8)
	/Users/matti/go/src/github.com/raff/goble/xpc/xpc.go:229 +0x242 fp=0xc42004de90 sp=0xc42004de20
github.com/raff/goble/xpc._cgoexpwrap_f507673fb4e8_handleXpcEvent(0x4a00ac0, 0xc420051de8)
	github.com/raff/goble/xpc/_obj/_cgo_gotypes.go:460 +0x35 fp=0xc42004deb0 sp=0xc42004de90
runtime.call32(0x0, 0x7000050d0248, 0x7000050d02e8, 0x10)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:514 +0x48 fp=0xc42004dee0 sp=0xc42004deb0
runtime.cgocallbackg1(0x0)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/cgocall.go:301 +0x19d fp=0xc42004df58 sp=0xc42004dee0
runtime.cgocallbackg(0x0)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/cgocall.go:184 +0x84 fp=0xc42004dfc0 sp=0xc42004df58
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:767 +0x74 fp=0xc42004dfe0 sp=0xc42004dfc0
runtime.goexit()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42004dfe8 sp=0xc42004dfe0
```

This could be just me misusing the library (or Golang, for I am quite a beginner with the language still), but with next to no documentation for the lib I am not sure..

So I am doing the Connect() call from within the AdvHandler func of my Scan() call. I have tried using the same exact context.Context as well as a fresh new one (allocated new one per each Connect() call) but neither way seems to work. Sometimes it crashes like this, sometimes Connect() succeeds but then the whole program gets stuck on ble.DiscoverProfile() (or ble.DiscoverServices()) call I am making, following the Connect().

I am running this on MacBook Pro PC, OSX Sierra 10.12.6, go version go1.8.1 darwin/amd64

- Matti

**Comment by matti777** [comment]
To me it seems like Scan() and Connect() are interfering with each other, even if I do the Connect() in a new goroutine. Should I abort the Scan() (using a context.WithTimeout() ?) before making the Connects() to the devices found?
