### ISSUE TITLE
osx: Error when exploring characteristic

### ISSUE THREAD

**Issue by deadprogram** [currantlabs/ble#8]
When testing on the latest OS X El Capitan using a LightBlue Bean device, I received the following error:

```
rons-MacBook-Air:examples ron$ ./bin/explorer --name="Bean"
Exploring Peripheral [ D7DE53F5A9824C3D80449C28A9543BE8 ] ...
Service: F000FFC004514000B000000000000000 
  Characteristic: F000FFC104514000B000000000000000, Property: 0x1C, 
    Descriptor: 2902, Client Characteristic Configuration
    Value         0000 | "\x00\x00"
    Descriptor: 2901, Characteristic User Description
panic: interface conversion: interface is string, not []uint8

goroutine 1 [running]:
panic(0x40de960, 0xc4200b8240)
	/Users/ron/.gvm/gos/go1.7beta2/src/runtime/panic.go:500 +0x1a1
github.com/currantlabs/ble/darwin.(*Client).ReadDescriptor(0xc4200c0000, 0xc4200ae780, 0xc420051da0, 0x2, 0x2, 0x36, 0x0)
	/Users/ron/.gvm/pkgsets/go1.7beta2/global/src/github.com/currantlabs/ble/darwin/client.go:165 +0x383
main.explorer(0x4170600, 0xc4200c0000, 0x4170600, 0xc4200c0000)
	/Users/ron/Development/ble/examples/explorer/main.go:69 +0x6c6
main.main()
	/Users/ron/Development/ble/examples/explorer/main.go:158 +0x27d
```

It appears that the type being returned by ReadDescriptor is not the same as the one that is expected.

**Comment by roylee17** [comment]
I'm also on El Captain. Let's dump the raw messages and see what we got :)

LOGXI=darwin go run explorer/main.go

**Comment by deadprogram** [comment]
OK, here is the output:

```
rons-MacBook-Air:examples ron$ LOGXI=darwin ./bin/explorer --name="Bean"
10:02:15.971690 INF darwin send id: 1
   args: map[kCBMsgArgName:gopher-1467446535 kCBMsgArgOptions:map[kCBInitOptionShowPowerAlert:1] kCBMsgArgType:0]
10:02:15.972793 INF darwin recv id: 6 args: map[kCBMsgArgState:5]
10:02:15.972973 INF darwin send id: 29
   args: map[kCBMsgArgOptions:map[kCBScanOptionAllowDuplicates:0]]
10:02:16.099241 INF darwin recv id: 37
   args: map[kCBMsgArgAdvertisementData:map[kCBAdvDataIsConnectable:1 kCBAdvDataTxPowerLevel:8] kCBMsgArgRssi:-60 kCBMsgArgDeviceUUID:e708e9dc75844d56a382c6edf19ec9fc kCBMsgArgName:2B-785E]
10:02:16.102376 INF darwin recv id: 37
   args: map[kCBMsgArgAdvertisementData:map[kCBAdvDataIsConnectable:1 kCBAdvDataServiceUUIDs:[[34 187 116 111 43 160 117 84 45 111 114 101 104 112 83 39]] kCBAdvDataLocalName:2B-785E] kCBMsgArgRssi:-61 kCBMsgArgDeviceUUID:e708e9dc75844d56a382c6edf19ec9fc kCBMsgArgName:2B-785E]
10:02:17.243715 INF darwin recv id: 37
   args: map[kCBMsgArgAdvertisementData:map[kCBAdvDataIsConnectable:1 kCBAdvDataServiceUUIDs:[[164 149 255 16 197 177 75 68 181 18 19 112 240 45 116 222]] kCBAdvDataTxPowerLevel:4] kCBMsgArgRssi:-57 kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgName:Bean]
10:02:17.243937 INF darwin send id: 30 args: map[]
10:02:17.244312 INF darwin send id: 31
   args: map[kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgOptions:map[kCBConnectOptionNotifyOnDisconnection:1]]
10:02:17.918631 INF darwin recv id: 38
   args: map[kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8]
Exploring Peripheral [ D7DE53F5A9824C3D80449C28A9543BE8 ] ...
10:02:17.919114 INF darwin send id: 45
   args: map[kCBMsgArgUUIDs:[] kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8]
10:02:17.919179 INF darwin recv id: 53
   args: map[kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgATTMTU:23]
10:02:17.920142 INF darwin recv id: 56
   args: map[kCBMsgArgServices:[map[kCBMsgArgServiceEndHandle:9 kCBMsgArgServiceStartHandle:1 kCBMsgArgUUID:[240 0 255 192 4 81 64 0 176 0 0 0 0 0 0 0]] map[kCBMsgArgServiceStartHandle:25 kCBMsgArgUUID:[24 10] kCBMsgArgServiceEndHandle:43] map[kCBMsgArgServiceStartHandle:44 kCBMsgArgUUID:[164 149 255 16 197 177 75 68 181 18 19 112 240 45 116 222] kCBMsgArgServiceEndHandle:48] map[kCBMsgArgServiceStartHandle:49 kCBMsgArgUUID:[164 149 255 32 197 177 75 68 181 18 19 112 240 45 116 222] kCBMsgArgServiceEndHandle:69] map[kCBMsgArgUUID:[24 15] kCBMsgArgServiceEndHandle:65535 kCBMsgArgServiceStartHandle:70]] kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgResult:0]
Service: F000FFC004514000B000000000000000 
10:02:17.920522 INF darwin send id: 62
   args: map[kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgServiceStartHandle:1 kCBMsgArgServiceEndHandle:9 kCBMsgArgUUIDs:[]]
10:02:18.092790 INF darwin recv id: 64
   args: map[kCBMsgArgCharacteristics:[map[kCBMsgArgCharacteristicValueHandle:3 kCBMsgArgCharacteristicHandle:2 kCBMsgArgCharacteristicProperties:28 kCBMsgArgUUID:[240 0 255 193 4 81 64 0 176 0 0 0 0 0 0 0]] map[kCBMsgArgCharacteristicProperties:28 kCBMsgArgUUID:[240 0 255 194 4 81 64 0 176 0 0 0 0 0 0 0] kCBMsgArgCharacteristicValueHandle:7 kCBMsgArgCharacteristicHandle:6]] kCBMsgArgServiceStartHandle:1 kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgResult:0]
  Characteristic: F000FFC104514000B000000000000000, Property: 0x1C (wWN), 
10:02:18.093134 INF darwin send id: 70
   args: map[kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgCharacteristicHandle:2 kCBMsgArgCharacteristicValueHandle:3 kCBMsgArgUUIDs:[]]
10:02:18.197832 INF darwin recv id: 76
   args: map[kCBMsgArgDescriptors:[map[kCBMsgArgUUID:[41 2] kCBMsgArgDescriptorHandle:4] map[kCBMsgArgUUID:[41 1] kCBMsgArgDescriptorHandle:5]] kCBMsgArgCharacteristicHandle:2 kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8]
    Descriptor: 2902, Client Characteristic Configuration
10:02:18.198163 INF darwin send id: 77
   args: map[kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgDescriptorHandle:4]
10:02:18.251598 INF darwin recv id: 81
   args: map[kCBMsgArgConnectionInterval:198 kCBMsgArgConnectionLatency:0 kCBMsgArgSupervisionTimeout:500 kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8]
10:02:18.648940 INF darwin recv id: 79
   args: map[kCBMsgArgData:[0 0] kCBMsgArgDescriptorHandle:4 kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgResult:0]
    Value         0000 | "\x00\x00"
    Descriptor: 2901, Characteristic User Description
10:02:18.649179 INF darwin send id: 77
   args: map[kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgDescriptorHandle:5]
10:02:19.046434 INF darwin recv id: 79
   args: map[kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgResult:0 kCBMsgArgData:Img Identify kCBMsgArgDescriptorHandle:5]
panic: interface conversion: interface is string, not []uint8

goroutine 1 [running]:
panic(0x4116ec0, 0xc4200d8580)
	/Users/ron/.gvm/gos/go1.7beta2/src/runtime/panic.go:500 +0x1a1
github.com/currantlabs/ble/darwin.(*Client).ReadDescriptor(0xc4200d8280, 0xc4200ceae0, 0xc4200b7dc0, 0x2, 0x2, 0x36, 0x0)
	/Users/ron/.gvm/pkgsets/go1.7beta2/global/src/github.com/currantlabs/ble/darwin/client.go:165 +0x383
main.explorer(0x41c6c40, 0xc4200d8280, 0x41c6c40, 0xc4200d8280)
	/Users/ron/Development/ble/examples/explorer/main.go:67 +0x728
main.main()
	/Users/ron/Development/ble/examples/explorer/main.go:164 +0x1ca
```

Thanks!

**Comment by roylee17** [comment]
So from the last two msg 79 (read descriptor), we do get different data types of the "kCBMsgArgData".

10:02:18.648940 INF darwin recv id: 79
   args: map[kCBMsgArgData:[0 0] kCBMsgArgDescriptorHandle:4 kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgResult:0]

10:02:19.046434 INF darwin recv id: 79
   args: map[kCBMsgArgDeviceUUID:d7de53f5a9824c3d80449c28a9543be8 kCBMsgArgResult:0 kCBMsgArgData:Img Identify kCBMsgArgDescriptorHandle:5]

Let me know if the latest commit fix the issue, thanks!

**Comment by deadprogram** [comment]
That fixed it, thanks @roylee17 

Closing.

**Comment by P-A-R-U-S** [comment]
Hi, I'm still getting similar issue.

2018/01/11 16:54:09 Unhandled event: xpc.Dict{"kCBMsgId":54, "kCBMsgArgs":xpc.Dict{"kCBMsgArgServiceStartHandle":10, "kCBMsgArgDeviceUUID":xpc.UUID{0xb1, 0xa0, 0x98, 0xf5, 0x42, 0xc8, 0x42, 0xbf, 0xa7, 0xe5, 0x74, 0x79, 0xbb, 0x25, 0xe0, 0x5}, "kCBMsgArgServiceEndHandle":65535}}

I have run basic example to Advertising the service on OSX El Capitan and tried to connect from iPhone Light Blue. Looks like you catch event, but not handle it.  

Do you have any details what kind of event it is and how it should be handled and I can add code to do this ?
<img width="1386" alt="screen shot 2018-01-11 at 5 22 56 pm" src="https://user-images.githubusercontent.com/1575452/34852427-3309ffbc-f6f4-11e7-98b4-9e4943b5765c.png">

**Comment by deadprogram** [comment]
Hello @P-A-R-U-S you might want to check out this fork, which has had a lot more recent development for OSX: https://github.com/go-ble/ble

**Comment by P-A-R-U-S** [comment]
Thank you @deadprogram. I will try. My plan to use same library both OSX and Raspberry Pi. Do you think it will work both ?

**Comment by deadprogram** [comment]
I think it is very likely. We do the same thing.

**Comment by P-A-R-U-S** [comment]
@deadprogram Looks like this event does not handle both here and https://github.com/go-ble/ble.

**Comment by deadprogram** [comment]
You should check out this branch https://github.com/go-ble/ble/pull/7 once that PR is merged, it should help your issue.
